# Prometheus configuration for MCP Kanban monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'mcp-kanban-monitor'

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # MCP Kanban API server
  - job_name: 'mcp-kanban-api'
    static_configs:
      - targets: ['mcp-kanban-api:3000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # MCP Kanban MCP server
  - job_name: 'mcp-kanban-mcp'
    static_configs:
      - targets: ['mcp-kanban-mcp:3001']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Health check endpoints
  - job_name: 'health-checks'
    static_configs:
      - targets: 
        - 'mcp-kanban-api:3000'
        - 'mcp-kanban-mcp:3001'
    metrics_path: '/health'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Grafana monitoring
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: '/metrics'

  # Loki monitoring
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
    metrics_path: '/metrics'